#!/bin/bash



source story
source roll
source chrsht
source functions


cat header



echo "











"

#NEW GAME FUNCTION
z="0"
# NGF REQUIRES Z TO = 0 TO START CHECK
#
#

ngf


echo "



"

echo "$a00
"

echo "$a01
"


echo "$a02
"


echo "$a03
"


echo "$a04
"


echo "$a05
"

echo "$a06
"

echo "  $a07
"

echo "  $a08
"
echo "$a09
"

#
#
#RANDOM CHECK RNDCHK
#REQUIRES AND X Y AND CHKV1 2 3 & 4 VALUES
#
#


x="$(rollnum 1d10)"
y="$(rollnum 1d10)"
chkv1="You take a deep breath and begin to feel at ease

    "
chkv2="  Beggar: Now don't go yakking just yet, we're almost to land.
"
chkv3="The beggar hands you a bag, knowing whats coming next.
    "
chkv4="    *You Vomit into the bag. Wiping the reamins on you torn rags of clothes.*
    "


rndchk

#
#END RANDOM CHECK
#



z="false"

#Charchter NAME INPUT #
while [ "$z" == "false" ];
do
    echo "  Beggar: So what's your name stranger...
    "
    read name

    echo "
    So $name is your name..."
    echo "
    Is that correct y/n
    "
    read yn

    if [[ "$yn" == "yes" || "$yn" == "Yes" || "$yn" == "y" || "$yn" == "Y" ]];
    then
        z="true"
    else
        z="false"
    fi

done





#variables for next question

myvar1="To fufill my legcy and be a heroic knight!"


myvar2="To attune myself with the magic of this world."


myvar3="To become as rich as I possibly can!
"



#Question 2#

z="false"

while [ "$z" == "false" ];
do


    echo "  Beggar: So $name what's your purpose here?

    "

    echo "  (a) $myvar1"
    echo "  (b) $myvar2"
    echo "  (c) $myvar3"

#
##
###Answer2
##
#

    read purpose


    if [[ "$purpose" == "a" || "$purpose" == "A" ]];
    then
        player=( "${warrior[@]}" )
        plyrhp=( "${warrior[1]}")
        echo "  Oh so you want to be a ${player[0]} "


        echo "
        The ${player[0]} stats are:
        ${player[1]}....HEALTH
        ${player[2]}....STRENGTH
        ${player[3]}....DEFENSE
        ${player[4]}....SPECIAL ATTACK
        ${player[5]}....SPECIAL DEFENCE
        ${player[6]} ...SPEED
        ${player[7]} ...MAGIC
      & ${player[8]}....LUCK."

        yesno

    elif [[ "$purpose" == "b" || "$purpose" == "B" ]];
    then
        player=( "${mage[@]}" )
        plyrhp=( "${mage[1]}")
        echo "  Oh so you want to be a ${player[0]} "


        echo "
        The ${player[0]} stats are:
        ${player[1]}....HEALTH
        ${player[2]}....STRENGTH
        ${player[3]}....DEFENSE
        ${player[4]}....SPECIAL ATTACK
        ${player[5]}....SPECIAL DEFENCE
        ${player[6]} ...SPEED
        ${player[7]} ...MAGIC
      & ${player[8]}....LUCK."


        yesno

    elif [[ "$purpose" == "c" || "$purpose" == "C" ]];
    then
        player=( "${rogue[@]}" )
        plyrhp=( "${rogue[1]}")
        echo "  Oh so you want to be a ${player[0]} "


        echo "
        The ${player[0]} stats are:
        ${player[1]}....HEALTH
        ${player[2]}....STRENGTH
        ${player[3]}....DEFENSE
        ${player[4]}....SPECIAL ATTACK
        ${player[5]}....SPECIAL DEFENCE
        ${player[6]} ...SPEED
        ${player[7]} ...MAGIC
      & ${player[8]}....LUCK.
      "

9
        yesno

    else
        echo "  Sorry I didn't quite catch that
        "
        z="false"
    fi
done


#Begin Story#

echo "$a10
"



echo "$a11
"

echo "$a12"




echo "$a13
"



echo "$a14"



echo "$a15
"



echo "$a16
"







#Question 3#

echo "  what do you do?
"

myvar1="You find some rags and burlap, and fashion them around yourself.
"
echo "  a. Look around for something to disuigse yourself"

myvar11="You've Been Caught!! The gaurds notice your odd apperance, and immediately recognize you. You are fashioned back in your shackles and hustled back into line.
"

myvar2="You see a small broken skiff, capsized in the sand
you crawl underneath. As best you can..
"
echo "  b. Hide and wait for your opprotunity to escape."

myvar21="You've Been Caught!! Your captors notice you feet sticking out from the boat.
You are fashioned back in your shackles and hustled back into line.
"

myvar3="You grab an oar and run for the nearest captor"
echo "  c. Grab the nearest object you can use as a weapon and advance on your captors.
"
myvar31="You've Been Caught!! Use lose your footing and fall face first before your captors.
You are fashioned back in your shackles and hustled back into line.
"

read answer3

str="${player[2]}"
lck="${player[8]}"
spd="${player[6]}"
x="$(rollnum 1d20)"
ans3="10"

if [ "$answer3" == "a" ]
then
    if [ "$lck" -gt "$chk" ]
    then
        droll="$(($lck - $chk))"
        echo "your have a +$droll modifier from luck
        "


        echo "you must roll a 10 out of 20 or higher
        "


        chk="$(($x + $droll))"

        echo "  you rolled a $chk"

    fi

    if [ $chk -gt $ans3 ]
    then
        echo "  Check Successful!
        "

        y="1"
        echo "$myvar1"
    else
        echo "  Check Failed!
        "
        y="0"
        echo "$myvar11"
    fi

elif [ "$answer3" == "b" ]
then
    if [ "$spd" -gt "$chk" ]
    then
        droll="$(($spd - $chk))"
        echo "your have a +$droll modifier from speed
        "


        echo "you must roll a 10 out of 20 or higher
        "


        chk="$(($x + $droll))"

        echo "  you rolled a $chk"

    fi

    if [ $chk -gt $ans3 ]
    then
        echo "  Check Successful!
        "
        y="1"

        echo "$myvar1"
    else
        echo "  Check Failed!
        "
        y="0"
        echo "$myvar21"
    fi

elif [ "$answer3" == "c" ]
then
    if [ "$str" -gt "$chk" ]
    then
        droll="$(($str - $chk))"
        echo "your have a +$droll modifier from Strength.
        "


        echo "you must roll a 10 out of 20 or higher.
        "


        chk="$(($x + $droll))"

        echo "  you rolled a $chk"

    fi

    if [ $chk -gt $ans3 ]
    then
        cmpn= "${stanger[@]}"
        echo "  Check Successful!
        "
        y="1"

        echo "$myvar1"
    else
        echo "  Check Failed!
        "
        y="0"
        echo "$myvar31"
    fi
fi
#story split for captor quest line#

if [ "$y" == "0" ]
then
    source ./sandbox/captors
fi






echo "$a17"












x="$(rollnum 1d20)"
ans="10"




#Question 4


echo "what do you do?
"

z="false"
q="false"

while [ "$q" == "false" ];
do

    echo " East or West?
    "

    read answer

#
#
#East Answer
#
#


    if [[ "$answer" == "east"  ||  "$answer" == "East" ]]
    then
        if [ "$z" == "false" ]
        then
            echo "  Perception Check!"

            if [ "$lck" -gt "$chk" ];
            then
                droll="$(($lck - $chk))"

                chk="$(($x + $droll))"
            fi
            if [ "$droll" == "0" ]
            then
                echo " you have no modifiers for luck."
            else
                echo "your have a +$droll modifier from luck
                "
            fi
                echo "you must roll a 10 out of 20 or higher
                "
                echo "  you rolled a $chk
                "

            if [ $chk -gt $ans ];
            then
                echo "  Check Successful!
                "
                echo "$b01"
                z="true"
                y="true"
            else
                echo "  Check Failed!
                "
                z="true"
                y="false"
                echo "You notice nothig of interest
                "
            fi
                echo "  Did you want to go east y/n?"
                read yn

            if [[ "$yn" == "yes" || "$yn" == "Yes" || "$yn" == "y" || "$yn" == "Y" ]];
            then
                q="true"
                z="true"
                ./sandbox/eastqst
            else
                q="false"
                z="true"
            fi
    else
        if [ "$y" == "true" ]
        then
            echo $b01
        fi
        echo "  Did you want to go east y/n?"

        read yn

            if [[ "$yn" == "yes" || "$yn" == "Yes" || "$yn" == "y" || "$yn" == "Y" ]];
            then
                q="true"
                z="true"
                ./sandbox/eastqst
            else
                q="false"
                z="true"
            fi
        fi
    fi

#
#
# West Answer
#
#
    if [[ "$answer" == "west"  ||  "$answer" == "West" ]]
    then
        if [ "$z" == "false" ]
        then
            echo "  Perception Check!"

            if [ "$lck" -gt "$chk" ];
            then
                droll="$(("$lck" - "$chk"))"
                chk="$(($x + $droll))"

            fi
            if [ "$droll" == "0" ]
            then
                echo " you have no modifiers for luck."
            else
                echo "your have a +$droll modifier from luck.
                "
            fi
                echo "you must roll a 10 out of 20 or higher.
                "
                echo "  you rolled a $chk!
                "

            if [ $chk -gt $ans ];
            then
                echo "  Check Successful!
                "
                echo "$c01"
                z="true"
                y="true"
            else
                echo "  Check Failed!
                "
                z="true"
                y="false"
                echo "You notice nothig of interest
                "
            fi
                echo "  Did you want to go west y/n?"
                read yn

            if [[ "$yn" == "yes" || "$yn" == "Yes" || "$yn" == "y" || "$yn" == "Y" ]];
            then
                q="true"
                z="true"
                ./sandbox/westqst
            else
                q="false"
                z="true"
            fi
    else
        if [ "$y" == "true" ]
        then
            echo $b01
        fi
        echo "  Did you want to go west y/n?"

        read yn

            if [[ "$yn" == "yes" || "$yn" == "Yes" || "$yn" == "y" || "$yn" == "Y" ]];
            then
                q="true"
                z="true"

               ./sandbox/westqst
            else
                q="false"
                z="true"
            fi
        fi
    fi

done

