#!/bin/bash



source /home/deck/Documents/Mygame/story
source /home/deck/Documents/Mygame/roll
source /home/deck/Documents/Mygame/chrsht

sleep 1.2
echo "

"

cat /home/deck/Documents/Mygame/header

sleep 2.5

echo "




"

z="0"

while [ "$z" == "0" ];
do
    echo "  Please type one of the options:"
    echo "  (a) Start New Game"
    echo "  (b) Load Game"
    read gamestate

    if [[ "$gamestate" == "b" || "$gamestate" == "B" ]]
    then
        echo "This Feature is currently not supported"
        z="0"
    elif [[ "$gamestate" == "a" || "$gamestate" == "A" ]]
    then
        echo "  Starting New Game...
        "

        z="1"
   else

       z="0"

   fi
done
echo "


"
sleep 2
echo "$a01"

sleep 2.5
echo "$a02
"
sleep 2.5

echo "$a03
"
sleep 2.5

echo "  $a04
"
sleep 2.5

echo "  $a05
"
sleep 2.5
echo "$a06
"
sleep 2.5

x="$(rollnum 1d10)"
y="$(rollnum 1d10)"

if [ "$x" -gt "$y" ];
then
    echo "  Check Sucessful!

    "
    sleep 2
    echo "You take a deep breath and begin to feel at ease

    "
    sleep 2
    echo "  Beggar: Now don't go yakking just yet, we're almost to land.
"
sleep 2.5
else
    echo "  Check Failed!

    "
    sleep 2
    echo "The beggar hands you a bag, knowing whats coming next.
    "
    sleep 2
    echo "*You Vomit into the bag. Wiping the reamins on you torn rags of clothes.*
    "
    sleep 2

fi







z="false"


#Charchter NAME INPUT #
while [ "$z" == "false" ];
do
    echo "  Beggar: So what's your name stranger...
    "
    read name
    sleep 1
    echo "
    So $name is your name..."
    echo "
    Is that correct y/n
    "
    sleep 1
    read yn

    if [[ "$yn" == "yes" || "$yn" == "Yes" || "$yn" == "y" || "$yn" == "Y" ]];
    then
        z="true"
    else
        z="false"
    fi
done





#variables for next question

myvar1="To fufill my legcy and be a heroic knight!"


myvar2="To attune myself with the magic of this world."


myvar3="To become as rich as I possibly can!
"



#Question 2#

z="false"

while [ "$z" == "false" ];
do

sleep 2.5
    echo "
    Beggar: So $name what's your purpose here?

    "
sleep 1
    echo "  (a) $myvar1"
    echo "  (b) $myvar2"
    echo "  (c) $myvar3"

#
##
###Answer2
##
#

    read purpose


    if [[ "$purpose" == "a" || "$purpose" == "A" ]];
    then
        player=( "${warrior[@]}" )
        plyrhp=( "${warrior[1]}")
        echo "Oh so you want to be a ${player[0]} "
        sleep 1

        echo "
        The ${player[0]} stats are:
        ${player[1]}....HEALTH
        ${player[2]}....STRENGTH
        ${player[3]}....DEFENSE
        ${player[4]}....SPECIAL ATTACK
        ${player[5]}....SPECIAL DEFENCE
        ${player[6]} ...SPEED
        ${player[7]} ...MAGIC
      & ${player[8]}....LUCK."

        sleep 1
        echo "  Are you sure? y/n?
        "
        read yn
        sleep 1
        if [[ "$yn" == "yes" || "$yn" == "Yes" || "$yn" == "y" || "$yn" == "Y" ]];
        then
            z="true"
        else
            z="false"
        fi
    elif [[ "$purpose" == "b" || "$purpose" == "B" ]];
    then
        player=( "${mage[@]}" )
        plyrhp=( "${mage[1]}")
        echo "Oh so you want to be a ${player[0]} "
        sleep 1

        echo "
        The ${player[0]} stats are:
        ${player[1]}....HEALTH
        ${player[2]}....STRENGTH
        ${player[3]}....DEFENSE
        ${player[4]}....SPECIAL ATTACK
        ${player[5]}....SPECIAL DEFENCE
        ${player[6]} ...SPEED
        ${player[7]} ...MAGIC
      & ${player[8]}....LUCK."
        sleep 1

        echo "  Are you sure? y/n?
        "
        read yn
        sleep 1
        if [[ "$yn" == "yes" || "$yn" == "Yes" || "$yn" == "y" || "$yn" == "Y" ]];
        then
            z="true"
        else
            z="false"
        fi

    elif [[ "$purpose" == "c" || "$purpose" == "C" ]];
    then
        player=( "${rogue[@]}" )
        plyrhp=( "${rogue[1]}")
        sleep 1
        echo "Oh so you want to be a ${player[0]} "

        sleep 1
        echo "
        The ${player[0]} stats are:
        ${player[1]}....HEALTH
        ${player[2]}....STRENGTH
        ${player[3]}....DEFENSE
        ${player[4]}....SPECIAL ATTACK
        ${player[5]}....SPECIAL DEFENCE
        ${player[6]} ...SPEED
        ${player[7]} ...MAGIC
      & ${player[8]}....LUCK.
      "
        sleep 1

        echo "

        Are you sure? y/n?
        "
        read yn
        sleep 1
        if [[ "$yn" == "yes" || "$yn" == "Yes" || "$yn" == "y" || "$yn" == "Y" ]];
        then
            z="true"
        else
            z="false"
        fi
    else
        echo "  Sorry I didn't quite catch that
        "
        sleep 1
        z="false"
    fi
done


#Begin Story#

echo "$a07
"

sleep 2.5

echo "$a08
"
sleep 2.5
echo "$a09"

sleep 2.5


echo "$a10
"

sleep 2.5

echo "$a11"

sleep 2.5

echo "$a12
"

sleep 2.5

echo "$a13
"

sleep 2.5




#Question 3#

echo "what do you do?"
sleep 1
myvar1="You find some rags and burlap, and fashion them around yourself.
"

echo "a. Look around for something to disuigse yourself"


myvar11="You've Been Caught!! The gaurds notice your odd apperance, and immediately recognize you. You are fashioned back in your shackles and hustled back into line.
"

myvar2="You see a small broken skiff, capsized in the sand
you crawl underneath. As best you can..
"
echo "b. Hide and wait for your opprotunity to escape."

myvar21="You've Been Caught!! Your captors notice you feet sticking out from the boat.
You are fashioned back in your shackles and hustled back into line.
"

myvar3="You grab an oar and run for the nearest captor"
echo "c. Grab the nearest object you can use as a weapon and advance on your captors.
"
myvar31="You've Been Caught!! Use lose your footing and fall face first before your captors.
You are fashioned back in your shackles and hustled back into line.
"

read answer3
sleep 1
str="${player[2]}"
lck="${player[8]}"
spd="${player[6]}"
x="$(rollnum 1d20)"
ans3="10"

if [ "$answer3" == "a" ]
then
    if [ "$lck" -gt "$chk" ]
    then
        droll="$(($lck - $chk))"

        echo "your have a +$droll modifier from luck
        "
        sleep 2.5

        echo "you must roll a 10 out of 20 or higher
        "
        sleep 2.5

        chk="$(($x + $droll))"

        echo "  you rolled a $chk"
        sleep 2.5
    fi

    if [ $chk -gt $ans3 ]
    then
        echo "  Check Successful!
        "
        sleep 2.5
        y="1"
        echo "$myvar1"
    else
        echo "  Check Failed!
        "
        sleep 2.5
        y="0"
        echo "$myvar11"
        sleep 2.5
    fi

elif [ "$answer3" == "b" ]
then
    if [ "$spd" -gt "$chk" ]
    then
        droll="$(($spd - $chk))"
        echo "your have a +$droll modifier from speed
        "
        sleep 2.5


        echo "you must roll a 10 out of 20 or higher
        "
        sleep 2.5


        chk="$(($x + $droll))"

        echo "  you rolled a $chk"
        sleep 2.5

    fi

    if [ $chk -gt $ans3 ]
    then
        echo "  Check Successful!
        "
        sleep 2.5
        y="1"

        echo "$myvar1"
    else
        echo "  Check Failed!
        "
        sleep 2.5
        y="0"
        echo "$myvar21"
        sleep 2.5
    fi

elif [ "$answer3" == "c" ]
then
    if [ "$str" -gt "$chk" ]
    then
        droll="$(($str - $chk))"
        echo "your have a +$droll modifier from Strength.
        "
        sleep 2.5


        echo "you must roll a 10 out of 20 or higher.
        "
        sleep 2.5


        chk="$(($x + $droll))"

        echo "  you rolled a $chk"
        sleep 2.5
    fi

    if [ $chk -gt $ans3 ]
    then
        cmpn= "${stanger[@]}"
        echo "  Check Successful!
        "
        sleep 2.5
        y="1"

        echo "$myvar1"
    else
        echo "  Check Failed!
        "
        sleep 2.5
        y="0"
        echo "$myvar31"
        sleep 2.5
    fi
fi
#story split for captor quest line#

if [ "$y" == "0" ]
then
    source ./sandbox/captors
fi



echo "$a14"

sleep 2.5

echo "$a15"

sleep 2.5

echo "$a16"

sleep 2.5

echo "$a17"

sleep 1.5










x="$(rollnum 1d20)"
ans="10"




#Question 4


echo "what do you do?
"
sleep 1

z="false"
q="false"

while [ "$q" == "false" ];
do

    echo " East or West?
    "

    read answer
    sleep 1
#
#
#East Answer
#
#


    if [[ "$answer" == "east"  ||  "$answer" == "East" ]]
    then
        if [ "$z" == "false" ]
        then
            echo "
            Perception Check!
            "
                sleep 2.5
            if [ "$lck" -gt "$chk" ];
            then
                droll="$(($lck - $chk))"

                chk="$(($x + $droll))"
            fi
            if [ "$droll" == "0" ]
            then
                echo " you have no modifiers for luck."
                sleep 2.5
            else
                echo "your have a +$droll modifier from luck
                "
                sleep 2.5
            fi
                echo "you must roll a 10 out of 20 or higher
                "
                sleep 2.5
                echo "  you rolled a $chk
                "
                sleep 2.5

            if [ $chk -gt $ans ];
            then
                echo "  Check Successful!
                "
                sleep 2.5
                echo "$b01"
                sleep 2.5
                z="true"
                y="true"
            else
                echo "  Check Failed!
                "
                sleep 2.5
                z="true"
                y="false"
                echo "You notice nothig of interest
                "
                sleep 2.5
            fi
                echo "  Did you want to go east y/n?"
                read yn
                sleep 2.5

            if [[ "$yn" == "yes" || "$yn" == "Yes" || "$yn" == "y" || "$yn" == "Y" ]];
            then
                q="true"
                z="true"
                ./sandbox/eastqst
            else
                q="false"
                z="true"
            fi
    else
        if [ "$y" == "true" ]
        then
            echo $b01
            sleep 2.5
        fi
        echo "  Did you want to go east y/n?"
        sleep 2.5
        read yn

            if [[ "$yn" == "yes" || "$yn" == "Yes" || "$yn" == "y" || "$yn" == "Y" ]];
            then
                q="true"
                z="true"
                ./sandbox/eastqst
            else
                q="false"
                z="true"
            fi
        fi
    fi

#
#
# West Answer
#
#
    if [[ "$answer" == "west"  ||  "$answer" == "West" ]]
    then
        if [ "$z" == "false" ]
        then
            echo "
            Perception Check!
            "
            sleep 2.5

            if [ "$lck" -gt "$chk" ];
            then
                droll="$(("$lck" - "$chk"))"
                chk="$(($x + $droll))"

            fi
            if [ "$droll" == "0" ]
            then
                echo " you have no modifiers for luck."
                sleep 2.5
            else
                echo "your have a +$droll modifier from luck.
                "
                sleep 2.5
            fi
                echo "you must roll a 10 out of 20 or higher.
                "
                sleep 2.5
                echo "  you rolled a $chk!
                "
                sleep 2.5

            if [ $chk -gt $ans ];
            then
                echo "  Check Successful!
                "
                sleep 2.5
                echo "$c01"
                sleep 2.5
                z="true"
                y="true"
            else
                echo "  Check Failed!
                "
                sleep 2.5
                z="true"
                y="false"
                echo "You notice nothig of interest
                "
                sleep 2.5
            fi
                echo "  Did you want to go west y/n?"
                read yn
                sleep 2.5

            if [[ "$yn" == "yes" || "$yn" == "Yes" || "$yn" == "y" || "$yn" == "Y" ]];
            then
                q="true"
                z="true"
                ./sandbox/westqst
            else
                q="false"
                z="true"
            fi
        else
            if [ "$y" == "true" ]
            then
                echo $b01
                sleep 2.5
            fi
            echo "  Did you want to go west y/n?"


            read yn

            if [[ "$yn" == "yes" || "$yn" == "Yes" || "$yn" == "y" || "$yn" == "Y" ]];
            then
                q="true"
                z="true"
                ./sandbox/westqst
            else
                q="false"
                z="true"
            fi
        fi
    fi

done

